# Copyright 2022 pietro
# See LICENSE file for licensing details.

options:
  rule:
    default:
    description: >
      A Traefik routing rule, see https://doc.traefik.io/traefik/routing/routers/ for
      an overview.

      The value of the field is going to be processed as a Jinja2 template, with the
      following globals available:
       - {{juju_model}} resolves to the model name of the downstream proxied 
         application.
       - {{juju_application}} resolves to the application name of the downstream 
         proxied application.
       - {{juju_unit}} resolves to the unit name of the downstream proxied unit;
         to avoid issues when used together with the Host directive or similar, 
         the slash character between application name and unit index is replaced with a dash.

      For example, given a downstream unit called `prometheus/0` in the `cos` model, the following:

        Host(`foo.bar/{{juju_model}}-{{juju_unit}}`)

      would evaluate to:

        Host(`foo.bar/cos-prometheus-0`)

    type: string

  url:
    default:
    description: >
      The url to advertise to the unit in need of ingress.

      The value of the field is going to be processed in exactly the same way as
      the `rule` field. The assumption is that the url is going to match
      the rule; however, we have no way to validate and/or enforce this condition;
      so beware!
      For example, given a downstream unit called `prometheus/0` in the `cos` model, the 
      following configuration is valid:

        rule="Host(`foo.bar/{{juju_model}}-{{juju_unit}}/`)"
        url="foo.bar/{{juju_model}}-{{juju_unit}}"
      
      while the following configuration is not:
      
        rule="Host(`foo.bar/{{juju_model}}-{{juju_unit}}`) || 
             HostRegexp(`{subdomain:[a-z]+}.foo.bar`) || 
             Host(`doobadooba.com`)"
        url="ab.foo.bar/{{juju_model}}-{{juju_unit}}"
      
      The reason why this is not valid is that the url does not match the rule:
      so the url advertised to the unit will not in fact be routed correctly by Traefik.
      Examples of good url values for this case would be:
      
        url="foo.bar/{{juju_model}}-{{juju_unit}}"
        url="baz.foo.bar" 
        url="qux.foo.bar" 
        url="doobadooba.com" 

    type: string
