# Copyright 2022 pietro
# See LICENSE file for licensing details.

options:
  rule:
    default:
    description: >
      A Traefik routing rule, see https://doc.traefik.io/traefik/routing/routers/ for
      an overview.

      The value of the field is going to be processed as a Jinja2 template, with the
      following globals available:
       - {{juju_model}} resolves to the model name of the downstream proxied 
         application.
       - {{juju_application}} resolves to the application name of the downstream 
         proxied application.
       - {{juju_unit}} resolves to the unit name of the downstream proxied unit;
         to avoid issues when used together with the Host directive or similar, 
         the slash character between application name and unit index is replaced with a dash.

      For example, given a downstream unit called `prometheus/0` in the `cos` model, the following:

        Host(`foo.bar/{{juju_model}}-{{juju_unit}}`)

      would evaluate to:

        Host(`foo.bar/cos-prometheus-0`)

    type: string
